baseURL: https://www.iothacking101.com/
languageCode: en-us
title: IoT Hacking 101
theme: tailwind
pygmentsUseClasses: true
#enableInlineShortcodes: true
enableEmoji: true
Copyright: 2024 | RFS
sectionPagesMenu: main
author: "RFS"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
  goldmark:
    renderer:
      unsafe: true
  _merge: "deep"

params:
  #showDescriptioninHome: true
  # hideAllTagsinHome: true
  searchBoxPlaceholder: "Type here to search..."
  titleIcon: logo.svg
  headers:
    key: Device
    value: Tags
    # value: Description

permalinks:
  tags: "@:slug"

taxonomies:
  category: "categories"
  tech: "technology"
  tag: "tags"
  rfid: "rfid"
  ble: "bluetooth"
  series: "series"

outputs:
  home:
    - HTML
    - RSS
    - JSON # for search

privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

menus:
  main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Technologies
    pageRef: /technologies
    weight: 20
  - name: Devices
    pageRef: /devices
    weight: 30
  - name: About
    pageRef: /about
    weight: 30


menus:
  footer:
  - name: Terms
    pageRef: /terms
    weight: 10
  - name: Privacy
    pageRef: /privacy
    weight: 20


