baseURL: https://www.iothacking101.com/
languageCode: en-us
title: IoT Hacking 101
theme: hugo-index
pygmentsUseClasses: true
#enableInlineShortcodes: true
Copyright: 2024 | RFS
sectionPagesMenu: main

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
  goldmark:
    renderer:
      unsafe: true

params:
  #showDescriptioninHome: true
  # hideAllTagsinHome: true
  searchBoxPlaceholder: "Type here to search..."
  titleIcon: logo.svg
  headers:
    key: Device
    value: Tags
    # value: Description

permalinks:
  tags: "@:slug"

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON # for search

privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

languages:
  pt:
    languageCode: pt-PT
    languageName: Portuguese
    menus:
      main:
      - name: Produtos
        pageRef: /produtos
        weight: 10
      - name: Serviços
        pageRef: /servicos
        weight: 20
    weight: 1
  en:
    languageCode: en-US
    languageName: English
    menus:
      main:
      - name: Products
        pageRef: /products
        weight: 10
      - name: Services
        pageRef: /services
        weight: 20
    weight: 2

menus:
  footer:
  - name: Terms
    pageRef: /terms
    weight: 10
  - name: Privacy
    pageRef: /privacy
    weight: 20